Summary:		It is an effective JPEG encoder
Name:			guetzli
Version:		1.0.1
Release:		4%{?dist}.gps
License:		ASL 2.0
Group:			Graphical desktop/Other
URL:			https://github.com/google/guetzli
Source0:		%{url}/archive/v%{version}.tar.gz
Source1:		guetzli.1
BuildRequires:	pkgconfig(libpng)
BuildRequires:	pkgconfig(libjpeg)

%description
Guetzli is a JPEG encoder that aims for excellent compression density 
at high visual quality. Guetzli-generated images are typically 20-30% 
smaller than images of equivalent quality generated by libjpeg. 

Guetzli generates only sequential (nonprogressive) JPEGs due to faster
decompression speeds they offer.


%package compare
Summary:	Show difference between original and Guetzli versions of an image
Requires:	guetzli
Requires:	butteraugli


%description compare
%{summary}


%prep
%autosetup -n %{name}-%{version}
%if 0%{?rhel} >= 8
  sed -i '1s@.*@#!/usr/libexec/platform-python@' tools/guetzli-compare.py
%endif
sed -i 's@\./butteraugli@%{_bindir}/butteraugli@' tools/guetzli-compare.py
sed -i 's@\./guetzli@%{_bindir}/guetzli@' tools/guetzli-compare.py

%build
%make_build


%install
%{__install} -Dpm0755 bin/Release/%{name} \
  %{buildroot}%{_bindir}/%{name}

%{__install} -Dpm0644 %{SOURCE1} \
  $RPM_BUILD_ROOT%{_mandir}/man1/guetzli.1

%{__install} -Dpm0755 tools/guetzli-compare.py \
  %{buildroot}%{_bindir}/guetzli-compare


%files
%license LICENSE 
%doc README.md 
%{_bindir}/%{name}
%{_mandir}/man1/guetzli.1*


%files compare
%{_bindir}/guetzli-compare


%changelog
* Mon Jul 15 2019 Danila Vershinin <info@getpagespeed.com> 1.0.1-4
- correct license tagging
- compare program subpackage with fixes for platform Python in EL8
- stop compiling butteraugli (in another package)
- man page

* Tue Sep 26 2017 Rosa <rosa@abf.rosalinux.ru> 1.0.1-1
- (0ef7f18) Automatic import for version 1.0.1-1


